routes/web.php
<?php

use App\Http\Controllers\Admin\ArtisanController;
use App\Http\Controllers\Admin\ContactFormController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\PageController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [PageController::class, 'index'])->name('home');

Route::get('/login', [PageController::class, 'login'])->name('login');
Route::get('/register', [PageController::class, 'register'])->name('register');

Route::get('/cart', [PageController::class, 'cart'])->name('shopping-cart');

Route::get('/orders/{order_guid}', [OrderController::class, 'show'])->name('order.show');
Route::post('/orders/new', [OrderController::class, 'store'])->name('order.new');

Route::group(['prefix' => 'admin', 'middleware' => 'is.admin'], function () {
    Route::resource('orders', App\Http\Controllers\Admin\OrderController::class);
    Route::resource('products', ProductController::class);
    Route::resource('users', UserController::class);
    Route::resource('forms', ContactFormController::class);

    Route::get('artisan/queue/run/worker', [ArtisanController::class, 'worker']);
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Product
 *
 * @property int $id
 * @property string $number
 * @property string $name
 * @property string $price
 * @property string|null $image
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|Product newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Product newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Product query()
 * @method static \Illuminate\Database\Eloquent\Builder|Product whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Product whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Product whereImage($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Product whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Product whereNumber($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Product wherePrice($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Product whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Product extends Model
{
    use HasFactory;

    protected $fillable = ['number', 'name', 'description', 'price'];

    public function carts() {
        return $this->belongsToMany(Cart::class, 'cart_product')->withPivot('amount');
    }

    public function orders() {
        return $this->belongsToMany(Order::class)->withPivot('amount');
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helpers\InputChecker;
use App\Http\Controllers\Controller;
use App\Models\Product;
use Exception;
use Illuminate\Http\Request;
use Ramsey\Uuid\Guid\Guid;
use Symfony\Component\Console\Input\Input;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::orderBy('price')->get();

        return view('admin.products.index', ['products' => $products]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = \request()->get('data');
        if (!$data) {
            return response([
                'code' => 'error',
                'title' => 'Oeps!',
                'message' => 'Er missen benodigde parameters.'
            ], 400);
        }

        $attributes = [];
        foreach ($data as $item) {
            $attributes[$item['name']] = $item['value'];
        }

        $attributes['price'] = $attributes['price'] * 100;
        $attributes['number'] = random_int(10000, 99999);

        $attributes = InputChecker::check($attributes, ['name', 'price', 'description']);
        if (!$attributes) {
            return response([
                'code' => 'error',
                'title' => 'Oeps!',
                'message' => 'Er missen benodigde parameters.'
            ], 400);
        }

        try {
            Product::create($attributes);
        } catch (Exception $exception) {
            return response([
                'code' => 'error',
                'title' => 'Oeps!',
                'message' => 'Er iets mis gegaan, neem contact op met de beheerders.'
            ], 400);
        }

        return response([
            'code' => 'success',
            'title' => 'Gelukt!',
            'message' => 'Het product is aangemaakt.'
        ], 200);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Product $product
     * @return array|\Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\Routing\ResponseFactory|\Illuminate\Http\Response
     */
    public function update(Product $product)
    {
        $data = \request()->get('data');
        if (!$data) {
            return response([
                'code' => 'error',
                'title' => 'Oeps!',
                'message' => 'Er missen benodigde parameters.'
            ], 400);
        }

        $attributes = [];
        foreach ($data as $item) {
            $attributes[$item['name']] = $item['value'];
        }

        $attributes['price'] = $attributes['price'] * 100;

        $attributes = InputChecker::check($attributes, ['name', 'price', 'description', 'image']);
        if (!$attributes) {
            return response([
                'code' => 'error',
                'title' => 'Oeps!',
                'message' => 'Er missen benodigde parameters.'
            ], 400);
        }

        try {
            $product->update($attributes);
        } catch (Exception $exception) {
            return response([
                'code' => 'error',
                'title' => 'Oeps!',
                'message' => 'Er iets mis gegaan, neem contact op met de beheerders.'
            ], 400);
        }

        return response([
            'code' => 'success',
            'title' => 'Gelukt!',
            'message' => 'Het product is aangepast.'
        ], 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Product $product
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\Routing\ResponseFactory|\Illuminate\Http\Response|void
     */
    public function destroy(Product $product)
    {
        try {
            $product->delete();
        } catch (Exception $exception) {
            return response([
                'code' => 'error',
                'title' => 'Oeps!',
                'message' => 'Er iets mis gegaan, neem contact op met de beheerders.'
            ], 400);
        }

        return response([
            'code' => 'success',
            'title' => 'Gelukt!',
            'message' => 'Het product is verwijderd.'
        ], 200);
    }
}

resources/views/admin/products/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="hero is-fullheight-with-navbar has-background-white-ter">
        <section class="hero-body">
            <div class="container box">

                @include('admin.modals.products.create')
                <button onclick="newProduct()" class="button rounded secondary-btn raised">Product toevoegen</button>

                <div class="title-wrapper has-text-centered">
                    <h2 class="title is-2">Producten</h2>
                    <h3 class="subtitle is-5 is-muted">Hier vind je een overzicht van alle producten.</h3>
                    <div class="divider is-centered"></div>
                </div>
                <div class="content-wrapper">
                    <div class="columns is-centered">
                        <div class="column has-text-centered">
                            @if($products)
                                <table class="table is-hoverable is-fullwidth">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Naam</th>
                                        <th>Beschrijving</th>
                                        <th>Prijs</th>
                                        <th>Afbeelding</th>
                                        <th class="has-text-centered">Aanpassen</th>
                                        <th class="has-text-centered">Verwijderen</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($products as $product)
                                        <tr>
                                            <td class="py-5">{{ $product->number }}</td>
                                            <td class="py-5">{{ $product->name }}</td>
                                            <td class="py-5">{{ $product->description }}</td>
                                            <td class="py-5">&euro; {{ $product->price / 100 }}</td>
                                            <td class="py-5"><a onclick="openImage({{ $product->id }})">Klik hier voor
                                                    de afbeelding</a></td>
                                            <td class="py-5">
                                                <button onclick="openModal({{ $product->id }})"
                                                        class="button is-info is-small is-rounded"><i
                                                        class="far fa-edit"></i></button>
                                            </td>
                                            <td class="py-5">
                                                <button onclick="remove({{ $product->id }})"
                                                        class="button is-danger is-small is-rounded"><i
                                                        class="far fa-trash-alt"></i></button>
                                            </td>
                                        </tr>

                                        @include('admin.modals.products.edit')
                                        @include('admin.modals.products.image')

                                    @endforeach
                                    </tbody>
                                </table>
                            @else
                                <h1 class="title is-6">Welkom bij de pagina voor het overzicht van de huidige
                                    producten, op het moment zijn er geen producten aangemaakt.</h1>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </section>

    <script type="application/javascript">

        const Toast = Swal.mixin({
            toast: true,
            position: 'top-end',
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true,
            didOpen: (toast) => {
                toast.addEventListener('mouseenter', Swal.stopTimer)
                toast.addEventListener('mouseleave', Swal.resumeTimer)
            }
        })

        function openModal(productID) {
            $('#modal_' + productID).addClass('is-active');
            $('html').addClass('is-clipped');
        }

        function closeModal(productID) {
            $('#modal_' + productID).removeClass('is-active');
            $('html').removeClass('is-clipped');
        }

        function openImage(productID) {
            $('#image_' + productID).addClass('is-active');
            $('html').addClass('is-clipped');
        }

        function closeImage(productID) {
            $('#image_' + productID).removeClass('is-active');
            $('html').removeClass('is-clipped');
        }

        function newProduct() {
            $('#modal_newProduct').addClass('is-active');
            $('html').addClass('is-clipped');
        }

        function cancelProduct() {
            $('form#newProduct :input').each(function () {
                let input = $(this);

                if (input.val()) {
                    return Swal.fire({
                        icon: 'warning',
                        title: 'Pas op!',
                        text: 'Weet je zeker dat je verder wilt gaan? De gegevens worden niet opgeslagen.',
                        showCancelButton: true,
                        confirmButtonText: 'Ja ik weet het zeker'
                    }).then((result) => {
                        if (result.isConfirmed) {
                            closeNewProduct();
                        }
                    })
                }

                closeNewProduct()
            });
        }

        function closeNewProduct() {
            $('#modal_newProduct').removeClass('is-active');
            $('html').removeClass('is-clipped');
        }

        function storeProduct() {
            let data = ($('form#newProduct').serializeArray());

            let oneIsEmpty = false;
            /* Check if information has no empty fields */
            $('form#newProduct :input').each(function () {
                let input = $(this);

                if (!input.val()) {
                    input.addClass('is-danger');
                    oneIsEmpty = true;
                }
            });

            if (!oneIsEmpty) {
                $.ajax({
                    type: 'POST',
                    url: '{{ route('api.products.store') }}',
                    data: {'data': data},
                    success: function (data) {
                        Toast.fire({
                            icon: data.code,
                            title: data.message
                        })

                        closeNewProduct()

                        window.setTimeout(function () {
                            location.reload()
                        }, 3000)
                    },
                    error: function (data) {
                        Toast.fire({
                            icon: data.responseJSON.code,
                            title: data.responseJSON.message
                        });
                    }
                })
            }
        }

        function update(productID) {
            let data = ($('form#update_' + productID).serializeArray());

            $.ajax({
                type: 'PATCH',
                url: '/api/products/' + productID,
                data: {'data': data},
                success: function (data) {
                    Toast.fire({
                        icon: data.code,
                        title: data.message
                    })

                    closeModal(productID)

                    window.setTimeout(function () {
                        location.reload()
                    }, 3000)
                },
                error: function (data) {
                    closeModal(productID);
                    Toast.fire({
                        icon: data.responseJSON.code,
                        title: data.responseJSON.message
                    });
                }
            });
        }

        function remove(productID) {
            Swal.fire({
                title: 'Pas op!',
                text: 'Weet je zeker dat je dit product wilt verwijderen?',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Ja ik weet het zeker'
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        type: 'DELETE',
                        url: '/api/products/' + productID,
                        success: function (data) {
                            Toast.fire({
                                icon: data.code,
                                title: data.message
                            })

                            closeModal(productID)

                            window.setTimeout(function () {
                                location.reload()
                            }, 3000)
                        },
                        error: function (data) {
                            closeModal(productID);
                            Toast.fire({
                                icon: data.responseJSON.code,
                                title: data.responseJSON.message
                            });
                        }
                    });
                }
            })
        }
    </script>
@endsection