routes/web.php
<?php

use App\Http\Controllers\Admin\ArtisanController;
use App\Http\Controllers\Admin\ContactFormController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\PageController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [PageController::class, 'index'])->name('home');

Route::get('/login', [PageController::class, 'login'])->name('login');
Route::get('/register', [PageController::class, 'register'])->name('register');

Route::get('/cart', [PageController::class, 'cart'])->name('shopping-cart');

Route::get('/orders/{order_guid}', [OrderController::class, 'show'])->name('order.show');
Route::post('/orders/new', [OrderController::class, 'store'])->name('order.new');

Route::group(['prefix' => 'admin', 'middleware' => 'is.admin'], function () {
    Route::resource('orders', App\Http\Controllers\Admin\OrderController::class);
    Route::resource('products', ProductController::class);
    Route::resource('users', UserController::class);
    Route::resource('forms', ContactFormController::class);

    Route::get('artisan/queue/run/worker', [ArtisanController::class, 'worker']);
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>Luther Constructie</title>

    {{-- Styles --}}
    <link type="text/css" href="{{ asset('css/main.css') }}" rel="stylesheet">
    <link type="text/css" href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">
    <script src="https://kit.fontawesome.com/272646e5db.js" crossorigin="anonymous"></script>

    {{-- Fonts --}}
    {{--<link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">--}}
    <link rel="icon" type="image/png" href="{{ asset('img/favicon.png') }}"/>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    {{-- CSRF Token --}}
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <style>
        html {
            scroll-behavior: smooth;
        }
    </style>

</head>

{{-- Scripts --}}
<script src="{{ \Illuminate\Support\Facades\URL::asset('js/app.js') }}"></script>
<script src="{{ asset('js/bundle.js') }}"></script>
<script src="https://unpkg.com/scrollreveal"></script>
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
        crossorigin="anonymous"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script type="module" src="https://unpkg.com/ionicons@5.0.0/dist/ionicons/ionicons.esm.js"></script>

<body>
<div id="app">
    @if(\Illuminate\Support\Facades\Route::is('home'))
        <div id="pageloader" class="pageloader"></div>
        <div id="infraloader" class="infraloader is-active"></div>
    @endif
    {{-- Header --}}
    @include('layouts.header')

    {{-- Content --}}
    @yield('content')

    {{-- Footer --}}
    @include('layouts.footer')

</div>
</body>
</html>

resources/views/layouts/footer.blade.php
<footer class="footer footer-dark">
    <div class="container">
        <div class="columns">
            <div class="column">
                <div class="footer-logo">
                    <h1 class="title is-4 has-text-weight-bold has-text-white">Luther Montage</h1>
                </div>
            </div>
            <div class="column">
                <div class="footer-column">
                    <div class="footer-header">
                        <h3>Product</h3>
                    </div>
                    <ul class="link-list">
                        <li><a href="#">Ontdek onze features</a></li>
                        <li><a href="#">Waarom ons product?</a></li>
                        <li><a href="#">Vergelijk features</a></li>
                        <li><a href="#">Onze Roadmap</a></li>
                        <li><a href="#">Vraag features aan</a></li>
                    </ul>
                </div>
            </div>
            <div class="column">
                <div class="footer-column">
                    <div class="footer-header">
                        <h3>Docs</h3>
                    </div>
                    <ul class="link-list">
                        <li><a href="#">Start hier</a></li>
                        <li><a href="#">Gebruikershandleiding</a></li>
                        <li><a href="#">Admin handleiding</a></li>
                        <li><a href="#">Developers</a></li>
                    </ul>
                </div>
            </div>
            <div class="column">
                <div class="footer-column">
                    <div class="footer-header">
                        <h3>Blogroll</h3>
                    </div>
                    <ul class="link-list">
                        <li><a href="#">Laatste news</a></li>
                        <li><a href="#">Tech artikelen</a></li>
                        <li><a href="#">Video Blog</a></li>
                    </ul>
                </div>
            </div>
            <div class="column">
                <div class="footer-column">
                    <div class="footer-header">
                        <h3>Volg ons</h3>
                        <nav class="level is-mobile">
                            <div class="level-left">
                                <a class="level-item" href="https://github.com/#">
                                        <span class="icon">
                                            <ion-icon name="logo-github" size="large"></ion-icon>
                                        </span>
                                </a>
                                <a class="level-item" href="https://facebook.com/#">
                                        <span class="icon">
                                            <ion-icon name="logo-facebook" size="large"></ion-icon>
                                        </span>
                                </a>
                                <a class="level-item" href="https://google.com/#">
                                        <span class="icon">
                                            <ion-icon name="logo-google" size="large"></ion-icon>
                                        </span>
                                </a>
                                <a class="level-item" href="https://linkedin.com/#">
                                        <span class="icon">
                                            <ion-icon name="logo-linkedin" size="large"></ion-icon>
                                        </span>
                                </a>
                            </div>
                        </nav>

                        <a href="https://bulma.io" target="_blank">
                            <img src="{{ asset('img/logo/made-with-bulma.png') }}" alt="Made with Bulma" width="128"
                                 height="24">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

<!-- Back To Top Button -->
<div x-data="initBackToTop()" x-on:scroll.window="scroll($event)" @click="goTop($event)" id="backtotop"><a
        href="javascript:" :class="{
        'visible': scrolled,
        '': !scrolled
    }"></a></div>

<div x-data="initSidebar()" class="sidebar" :class="{
            'is-active': $store.app.isSiderbarOpen,
            '': !$store.app.isSiderbarOpen
        }">
    <div class="sidebar-header">
        <img src="{{ asset('img/logo/fresh-square.svg') }}">
        <a @click="closeSidebar()" class="sidebar-close" href="javascript:void(0);"><i data-feather="x"></i></a>
    </div>
    <div class="inner">
        <ul class="sidebar-menu">
            <li><span class="nav-section-title"></span></li>

            <li>
                <a href="{{ route('orders.index') }}">
                    <span class="material-icons">local_shipping</span>
                    <span>Bestellingen</span>
                </a>
            </li>
            <li>
                <a href="{{ route('products.index') }}">
                    <span class="material-icons">inventory_2</span>
                    <span>Producten</span>
                </a>
            </li>
            <li>
                <a href="{{ route('forms.index') }}">
                    <span class="material-icons">email</span>
                    <span>Contact aanvragen</span>
                </a>
            </li>

{{--            <li @click="openSidebarMenu($event)" data-menu="sidebar-menu-1" class="have-children" :class="{--}}
{{--                        'active': openedMenu === 'sidebar-menu-1',--}}
{{--                        '': openedMenu != 'sidebar-menu-1'--}}
{{--                    }">--}}
{{--                <a href="#">--}}
{{--                    <span class="material-icons">apps</span>--}}
{{--                    <span>Overzicht</span>--}}
{{--                </a>--}}
{{--                <ul x-show.transition="openedMenu === 'sidebar-menu-1'">--}}
{{--                </ul>--}}
{{--            </li>--}}
{{--            <li @click="openSidebarMenu($event)" data-menu="sidebar-menu-2" class="have-children" :class="{--}}
{{--                        'active': openedMenu === 'sidebar-menu-2',--}}
{{--                        '': openedMenu != 'sidebar-menu-2'--}}
{{--                    }">--}}
{{--                <a href="#">--}}
{{--                    <span class="material-icons">duo</span>--}}
{{--                    <span>Messages</span>--}}
{{--                </a>--}}
{{--                <ul x-show.transition="openedMenu === 'sidebar-menu-2'">--}}
{{--                    <li><a href="#">Inbox</a></li>--}}
{{--                    <li><a href="#">Compose</a></li>--}}
{{--                    <li><a href="#">Video</a></li>--}}
{{--                </ul>--}}
{{--            </li>--}}
{{--            <li @click="openSidebarMenu($event)" data-menu="sidebar-menu-3" class="have-children" :class="{--}}
{{--                        'active': openedMenu === 'sidebar-menu-3',--}}
{{--                        '': openedMenu != 'sidebar-menu-3'--}}
{{--                    }">--}}
{{--                <a href="#">--}}
{{--                    <span class="material-icons">insert_photo</span>--}}
{{--                    <span>Media</span>--}}
{{--                </a>--}}
{{--                <ul x-show.transition="openedMenu === 'sidebar-menu-3'">--}}
{{--                    <li><a href="#">Library</a></li>--}}
{{--                    <li><a href="#">Upload</a></li>--}}
{{--                </ul>--}}
{{--            </li>--}}
{{--            <li @click="openSidebarMenu($event)" data-menu="sidebar-menu-4" class="have-children" :class="{--}}
{{--                        'active': openedMenu === 'sidebar-menu-4',--}}
{{--                        '': openedMenu != 'sidebar-menu-4'--}}
{{--                    }">--}}
{{--                <a href="#">--}}
{{--                    <span class="material-icons">policy</span>--}}
{{--                    <span>Settings</span>--}}
{{--                </a>--}}
{{--                <ul x-show.transition="openedMenu === 'sidebar-menu-4'">--}}
{{--                    <li><a href="#">User settings</a></li>--}}
{{--                    <li><a href="#">App settings</a></li>--}}
{{--                </ul>--}}
{{--            </li>--}}
        </ul>
    </div>
</div>

resources/views/layouts/header.blade.php
<nav x-data="initNavbar()" class="navbar is-fresh is-transparent no-shadow" role="navigation"
     aria-label="main navigation">
    <div class="container">
        <div class="navbar-brand">
            <a class="navbar-item" href="{{ route('home') }}">
                {{--                <img src="{{ asset('img/logo/fresh-alt.svg') }}" alt="" width="112" height="28">--}}
                Luther Montage
            </a>

            <a @click="openSidebar()" class="navbar-item is-hidden-desktop is-hidden-tablet">
                <div id="menu-icon-wrapper" class="menu-icon-wrapper" style="visibility: visible;" :class="{
                                'open': $store.app.isSiderbarOpen,
                                '': !$store.app.isSiderbarOpen
                            }">
                    <svg width="1000px" height="1000px">
                        <path class="path1"
                              d="M 300 400 L 700 400 C 900 400 900 750 600 850 A 400 400 0 0 1 200 200 L 800 800"></path>
                        <path class="path2" d="M 300 500 L 700 500"></path>
                        <path class="path3"
                              d="M 700 600 L 300 600 C 100 600 100 200 400 150 A 400 380 0 1 1 200 800 L 800 200"></path>
                    </svg>
                    <button id="menu-icon-trigger" class="menu-icon-trigger"></button>
                </div>
            </a>

            <div class="navbar-burger" @click="openMobileMenu()">
                        <span class="menu-toggle">
                            <span class="icon-box-toggle" :class="{
                                    'active': mobileOpen,
                                    '': !mobileOpen
                                }">
                                <span class="rotate">
                                    <i class="icon-line-top"></i>
                                    <i class="icon-line-center"></i>
                                    <i class="icon-line-bottom"></i>
                                </span>
                            </span>
                        </span>
            </div>
        </div>

        <div id="navbar-menu" class="navbar-menu is-static" :class="{
                        'is-active': mobileOpen,
                        '': !mobileOpen
                    }">

            <div class="navbar-start">
                @auth()
                    @if(auth()->user()->isAdmin())
                        <a @click="openSidebar()" class="navbar-item is-hidden-mobile">
                            <div id="menu-icon-wrapper" class="menu-icon-wrapper" style="visibility: visible;" :class="{
                                    'open': $store.app.isSiderbarOpen,
                                    '': !$store.app.isSiderbarOpen
                                }">
                                <svg width="1000px" height="1000px">
                                    <path class="path1"
                                          d="M 300 400 L 700 400 C 900 400 900 750 600 850 A 400 400 0 0 1 200 200 L 800 800">
                                    </path>
                                    <path class="path2" d="M 300 500 L 700 500"></path>
                                    <path class="path3"
                                          d="M 700 600 L 300 600 C 100 600 100 200 400 150 A 400 380 0 1 1 200 800 L 800 200">
                                    </path>
                                </svg>
                                <button id="menu-icon-trigger" class="menu-icon-trigger"></button>
                            </div>
                        </a>
                    @endif
                @endauth

                <a href="{{ route('shopping-cart') }}" class="navbar-item has-text-centered-tablet">
                    <i class="fas fa-shopping-basket"></i>
                </a>
            </div>

            <div class="navbar-end">
                @if(\Illuminate\Support\Facades\Route::is('home'))
                    <a href="#home" data-target="home" class="navbar-item is-secondary">
                        Home
                    </a>
                    <a href="#features" data-target="features" class="navbar-item is-secondary">
                        Diensten
                    </a>
                    <a href="#reviews" data-target="reviews" class="navbar-item is-secondary">
                        Reviews
                    </a>
                    <a href="#pricing" data-target="pricing" class="navbar-item is-secondary">
                        Producten
                    </a>
                    <a href="#contact" data-target="pricing" class="navbar-item is-secondary">
                        Contact
                    </a>
                @endif
                @guest()
                    <a {{--href="{{ route('login') }}"--}} onclick="openAuth()" class="navbar-item is-secondary modal-trigger"
                       data-modal="auth-modal">
                        Inloggen
                    </a>
                    <a {{--href="{{ route('register') }}"--}} onclick="openAuth()" class="navbar-item">
                            <span class="button signup-button rounded secondary-btn raised">
                                Registreren
                            </span>
                    </a>
                @endguest
            </div>
        </div>
    </div>
</nav>
<nav x-data="initNavbar()" x-on:scroll.window="scroll()" id="navbar-clone" class="navbar is-fresh is-transparent"
     role="navigation" aria-label="main navigation" :class="{
                'is-active': scrolled,
                '': !scrolled
            }">
    <div class="container">
        <div class="navbar-brand">
            <a class="navbar-item" href="{{ route('home') }}">
                {{--                <img src="{{ asset('img/logo/fresh-alt.svg') }}" alt="" width="112" height="28">--}}
                Luther Montage
            </a>

            <a @click="openSidebar()" class="navbar-item is-hidden-desktop is-hidden-tablet">
                <div id="menu-icon-wrapper" class="menu-icon-wrapper" style="visibility: visible;" :class="{
                                'open': $store.app.isSiderbarOpen,
                                '': !$store.app.isSiderbarOpen
                            }">
                    <svg width="1000px" height="1000px">
                        <path class="path1"
                              d="M 300 400 L 700 400 C 900 400 900 750 600 850 A 400 400 0 0 1 200 200 L 800 800"></path>
                        <path class="path2" d="M 300 500 L 700 500"></path>
                        <path class="path3"
                              d="M 700 600 L 300 600 C 100 600 100 200 400 150 A 400 380 0 1 1 200 800 L 800 200"></path>
                    </svg>
                    <button id="menu-icon-trigger" class="menu-icon-trigger"></button>
                </div>
            </a>

            <div class="navbar-burger" @click="openMobileMenu()">
                        <span class="menu-toggle">
                            <span class="icon-box-toggle" :class="{
                                    'active': mobileOpen,
                                    '': !mobileOpen
                                }">
                                <span class="rotate">
                                    <i class="icon-line-top"></i>
                                    <i class="icon-line-center"></i>
                                    <i class="icon-line-bottom"></i>
                                </span>
                            </span>
                        </span>
            </div>
        </div>

        <div id="cloned-navbar-menu" class="navbar-menu is-fixed" :class="{
                        'is-active': mobileOpen,
                        '': !mobileOpen
                    }">

            <div class="navbar-start">
                @auth()
                    @if(auth()->user()->isAdmin())
                        <a @click="openSidebar()" class="navbar-item is-hidden-mobile">
                            <div id="cloned-menu-icon-wrapper" class="menu-icon-wrapper" style="visibility: visible;"
                                 :class="{
                                    'open': $store.app.isSiderbarOpen,
                                    '': !$store.app.isSiderbarOpen
                                }">
                                <svg width="1000px" height="1000px">
                                    <path class="path1"
                                          d="M 300 400 L 700 400 C 900 400 900 750 600 850 A 400 400 0 0 1 200 200 L 800 800"></path>
                                    <path class="path2" d="M 300 500 L 700 500"></path>
                                    <path class="path3"
                                          d="M 700 600 L 300 600 C 100 600 100 200 400 150 A 400 380 0 1 1 200 800 L 800 200"></path>
                                </svg>
                                <button id="cloned-menu-icon-trigger" class="menu-icon-trigger"></button>
                            </div>
                        </a>
                    @endif
                @endauth

                <a href="{{ route('shopping-cart') }}" class="navbar-item has-text-centered-tablet-only">
                    <i class="fas fa-shopping-basket"></i>
                </a>
            </div>

            <div class="navbar-end">
                @if(\Illuminate\Support\Facades\Route::is('home'))
                    <a href="#home" data-target="home" class="navbar-item is-secondary">
                        Home
                    </a>
                    <a href="#features" data-target="features" class="navbar-item is-secondary">
                        Diensten
                    </a>
                    <a href="#reviews" data-target="reviews" class="navbar-item is-secondary">
                        Reviews
                    </a>
                    <a href="#pricing" data-target="pricing" class="navbar-item is-secondary">
                        Producten
                    </a>
                    <a href="#contact" data-target="pricing" class="navbar-item is-secondary">
                        Contact
                    </a>
                @endif
                @guest()
                    <a onclick="openAuth()" class="navbar-item is-secondary modal-trigger"
                       data-modal="auth-modal">
                        Inloggen
                    </a>
                    <a onclick="openAuth()" class="navbar-item">
                            <span class="button signup-button rounded secondary-btn raised">
                                Registreren
                            </span>
                    </a>
                @endguest
            </div>
        </div>
    </div>
</nav>

@include('modals.auth.show')